- - wrist_flex_joint:
      const_damping_torque_deadband: 3.0e-05
      const_external_torque_deadband: 0.025
      const_friction_torque_deadband: 0.0006
      const_ic_damping: 0.07006
      const_ic_inertia: 0.008
      const_ic_joint_stiffness: 6.343292
      const_ic_kinematic_friction: 1.5e-05
      const_ic_spring_coefficient: 0.2084
      const_ic_switch_external_torque: 1.0
      const_ic_viscous_friction: 0.0001
      const_spring_torque_limit: 0.3
      ref_feedforward_torque: 0.0
